"""add whatsapp_details_richtext to clients

Revision ID: 09047e8fa54c
Revises: a31092c4a1b3
Create Date: 2026-02-21 18:32:39.008946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09047e8fa54c'
down_revision: Union[str, Sequence[str], None] = 'a31092c4a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('whatsapp_details_richtext', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'whatsapp_details_richtext')
    # ### end Alembic commands ###
