"""Add webhook_logs table

Revision ID: 43f450d0d72e
Revises: 664debb5246d
Create Date: 2025-12-13 05:55:41.253482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f450d0d72e'
down_revision: Union[str, Sequence[str], None] = '664debb5246d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('is_retry', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_asset_id'), 'webhook_logs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_client_id'), 'webhook_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_created_at'), 'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_delivery_id'), 'webhook_logs', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_is_test'), 'webhook_logs', ['is_test'], unique=False)
    op.create_index(op.f('ix_webhook_logs_success'), 'webhook_logs', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_success'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_is_test'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_delivery_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_created_at'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_client_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_asset_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
