"""Initial database schema

Revision ID: 664debb5246d
Revises: 
Create Date: 2025-12-12 12:51:47.102208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664debb5246d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('batch_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=True),
    sa.Column('asset_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_queue_id'), 'batch_queue', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('default_credit_cost', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_active'), 'campaigns', ['active'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('google_sheet_id', sa.String(length=255), nullable=True),
    sa.Column('accept_sms', sa.Boolean(), nullable=True),
    sa.Column('accept_email', sa.Boolean(), nullable=True),
    sa.Column('accept_webhook', sa.Boolean(), nullable=True),
    sa.Column('accept_sheets', sa.Boolean(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('time_windows', sa.JSON(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('credits_balance', sa.Float(), nullable=True),
    sa.Column('credit_cost_per_lead', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('password_protected_link_token', sa.String(length=255), nullable=False),
    sa.Column('client_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_protected_link_token')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('captcha_type', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    op.create_index(op.f('ix_landing_pages_slug'), 'landing_pages', ['slug'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('landing_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('geo', sa.JSON(), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dedupe_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['landing_id'], ['landing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_mobile'), 'assets', ['mobile'], unique=True)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.String(length=50), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('credit_charged', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_asset_id'), 'deliveries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_deliveries_client_id'), 'deliveries', ['client_id'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_success'), 'deliveries', ['success'], unique=False)
    op.create_index(op.f('ix_deliveries_timestamp'), 'deliveries', ['timestamp'], unique=False)
    op.create_table('dlq',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlq_asset_id'), 'dlq', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dlq_client_id'), 'dlq', ['client_id'], unique=False)
    op.create_index(op.f('ix_dlq_created_at'), 'dlq', ['created_at'], unique=False)
    op.create_index(op.f('ix_dlq_id'), 'dlq', ['id'], unique=False)
    op.create_table('stored_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_leads_asset_id'), 'stored_leads', ['asset_id'], unique=False)
    op.create_index(op.f('ix_stored_leads_created_at'), 'stored_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_stored_leads_id'), 'stored_leads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_leads_id'), table_name='stored_leads')
    op.drop_index(op.f('ix_stored_leads_created_at'), table_name='stored_leads')
    op.drop_index(op.f('ix_stored_leads_asset_id'), table_name='stored_leads')
    op.drop_table('stored_leads')
    op.drop_index(op.f('ix_dlq_id'), table_name='dlq')
    op.drop_index(op.f('ix_dlq_created_at'), table_name='dlq')
    op.drop_index(op.f('ix_dlq_client_id'), table_name='dlq')
    op.drop_index(op.f('ix_dlq_asset_id'), table_name='dlq')
    op.drop_table('dlq')
    op.drop_index(op.f('ix_deliveries_timestamp'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_success'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_client_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_asset_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_mobile'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_landing_pages_slug'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_active'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_batch_queue_id'), table_name='batch_queue')
    op.drop_table('batch_queue')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
