"""Add import_history table

Revision ID: 9242b1ed3f37
Revises: 43f450d0d72e
Create Date: 2025-12-13 06:15:47.568922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9242b1ed3f37'
down_revision: Union[str, Sequence[str], None] = '43f450d0d72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('landing_page_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('successful_imports', sa.Integer(), nullable=True),
    sa.Column('failed_imports', sa.Integer(), nullable=True),
    sa.Column('duplicate_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('can_rollback', sa.Boolean(), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_history_admin_user_id'), 'import_history', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_import_history_campaign_id'), 'import_history', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_import_history_created_at'), 'import_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_history_id'), 'import_history', ['id'], unique=False)
    op.create_index(op.f('ix_import_history_landing_page_id'), 'import_history', ['landing_page_id'], unique=False)
    op.create_index(op.f('ix_import_history_rolled_back'), 'import_history', ['rolled_back'], unique=False)
    op.create_index(op.f('ix_import_history_status'), 'import_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_history_status'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_rolled_back'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_landing_page_id'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_id'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_created_at'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_campaign_id'), table_name='import_history')
    op.drop_index(op.f('ix_import_history_admin_user_id'), table_name='import_history')
    op.drop_table('import_history')
    # ### end Alembic commands ###
