"""add has_whatsapp fields to assets

Revision ID: a31092c4a1b3
Revises: be474161a1a0
Create Date: 2026-02-21 15:48:34.662297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31092c4a1b3'
down_revision: Union[str, Sequence[str], None] = 'be474161a1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('has_whatsapp', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('has_whatsapp_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'has_whatsapp_checked_at')
    op.drop_column('assets', 'has_whatsapp')
    # ### end Alembic commands ###
