"""Add advanced features tables (notes, tags, custom fields, scoring)

Revision ID: fb2e85ecc260
Revises: 685c3f23b276
Create Date: 2025-12-13 06:55:26.500714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb2e85ecc260'
down_revision: Union[str, Sequence[str], None] = '685c3f23b276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'SELECT', 'MULTISELECT', 'URL', 'EMAIL', 'PHONE', name='fieldtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('show_in_list', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_field_type'), 'custom_fields', ['field_type'], unique=False)
    op.create_index(op.f('ix_custom_fields_id'), 'custom_fields', ['id'], unique=False)
    op.create_index(op.f('ix_custom_fields_is_active'), 'custom_fields', ['is_active'], unique=False)
    op.create_index(op.f('ix_custom_fields_name'), 'custom_fields', ['name'], unique=True)
    op.create_table('lead_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_tags_id'), 'lead_tags', ['id'], unique=False)
    op.create_index(op.f('ix_lead_tags_name'), 'lead_tags', ['name'], unique=True)
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['lead_tags.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    op.create_index(op.f('ix_asset_tags_asset_id'), 'asset_tags', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_tags_tag_id'), 'asset_tags', ['tag_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_values_asset_id'), 'custom_field_values', ['asset_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_custom_field_id'), 'custom_field_values', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_id'), 'custom_field_values', ['id'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_by_client_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_asset_id'), 'lead_notes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_created_at'), 'lead_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_notes_created_by_admin_id'), 'lead_notes', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_created_by_client_id'), 'lead_notes', ['created_by_client_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_is_pinned'), 'lead_notes', ['is_pinned'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('score_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_asset_id'), 'lead_scores', ['asset_id'], unique=True)
    op.create_index(op.f('ix_lead_scores_grade'), 'lead_scores', ['grade'], unique=False)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_score'), 'lead_scores', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_scores_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_grade'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_asset_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_lead_notes_is_pinned'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_created_by_client_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_created_by_admin_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_created_at'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_asset_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_custom_field_values_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_custom_field_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_asset_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_asset_tags_tag_id'), table_name='asset_tags')
    op.drop_index(op.f('ix_asset_tags_asset_id'), table_name='asset_tags')
    op.drop_table('asset_tags')
    op.drop_index(op.f('ix_lead_tags_name'), table_name='lead_tags')
    op.drop_index(op.f('ix_lead_tags_id'), table_name='lead_tags')
    op.drop_table('lead_tags')
    op.drop_index(op.f('ix_custom_fields_name'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_is_active'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_field_type'), table_name='custom_fields')
    op.drop_table('custom_fields')
    # ### end Alembic commands ###
